<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>de.MCmoderSD</groupId>
    <artifactId>NASA-API</artifactId>
    <version>1.0.3</version>

    <name>NASA-API</name>
    <description>A lightweight Java wrapper for NASA's Open APIs</description>
    <url>https://github.com/MCmoderSD/NASA-API</url>

    <licenses>
        <license>
            <name>BSD 3-Clause License</name>
            <url>https://github.com/MCmoderSD/NASA-API/blob/master/LICENSE</url>
            <distribution>repo</distribution>
        </license>
    </licenses>

    <scm>
        <url>https://github.com/MCmoderSD/NASA-API</url>
        <connection>scm:git:https://github.com/MCmoderSD/NASA-API.git</connection>
        <developerConnection>scm:git:https://github.com/MCmoderSD/NASA-API.git</developerConnection>
    </scm>

    <distributionManagement>
        <repository>
            <id>Nexus</id>
            <name>Sonatype Nexus</name>
            <url>https://mcmodersd.de/nexus/repository/maven-releases/</url>
        </repository>
    </distributionManagement>

    <properties>
        <maven.compiler.source>25</maven.compiler.source>
        <maven.compiler.target>25</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>

        <!-- Jackson Databind -->
        <dependency>
            <groupId>tools.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>3.2.2</version>
        </dependency>

        <!-- TwelveMonkeys Core -->
        <dependency>
            <groupId>com.twelvemonkeys.imageio</groupId>
            <artifactId>imageio-core</artifactId>
            <version>3.15.1</version>
        </dependency>

        <!-- JPEG -->
        <dependency>
            <groupId>com.twelvemonkeys.imageio</groupId>
            <artifactId>imageio-jpeg</artifactId>
            <version>3.15.1</version>
        </dependency>

        <!-- BMP -->
        <dependency>
            <groupId>com.twelvemonkeys.imageio</groupId>
            <artifactId>imageio-bmp</artifactId>
            <version>3.15.1</version>
        </dependency>

        <!-- TIFF -->
        <dependency>
            <groupId>com.twelvemonkeys.imageio</groupId>
            <artifactId>imageio-tiff</artifactId>
            <version>3.15.1</version>
        </dependency>

        <!-- WebP -->
        <dependency>
            <groupId>com.twelvemonkeys.imageio</groupId>
            <artifactId>imageio-webp</artifactId>
            <version>3.15.0</version>
        </dependency>

        <!-- Annotations -->
        <dependency>
            <groupId>org.jetbrains</groupId>
            <artifactId>annotations</artifactId>
            <version>26.1.0</version>
        </dependency>

    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
                <version>3.4.0</version>
                <executions>
                    <execution>
                        <id>attach-sources</id>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>